### ISSUE TITLE
Default Kibana Dashboard key/value needs to be added to the Ansible role. 

### ISSUE THREAD

**Issue by dm00000** [5thColumn/ansible-role-elastic-stack-5.x#16]
https://github.com/elastic/kibana/issues/3777

kibana.defaultAppId: "dashboard/id"

**Comment by ajrgrubbs** [comment]
This is already supported, as shown in [the default variables](../blob/master/defaults/main.yml), which is then applied [here](../blob/master/templates/kibana/kibana.yml.j2). Can be implemented in the ansible role like:

```yaml
- role: elastic-stack-5.x
  install_kibana: yes
  kb_yml:
    kibana.defaultAppId: your_custom_value
```
