### ISSUE TITLE
Extra_config params break when a single-line is given

### ISSUE THREAD

**Issue by ajrgrubbs** [5thColumn/ansible-role-elastic-stack-5.x#33]
For example, the following (semantically equal) blocks should all work:

```yaml
extra_config:
  logger.deprecation.level: warn
```

```yaml
extra_config:
  logger.deprecation:
    level: warn
```

```yaml
extra_config:
  logger:
    deprecation:
      level: warn
```

The first breaks, the second and third work.
